# Generated by Django 3.1.7 on 2021-03-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('shortname', models.CharField(max_length=20, null=True)),
                ('codename', models.CharField(max_length=5, null=True)),
                ('VAT_Number', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('tax_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('office_notes', models.TextField(blank=True, default='', null=True)),
                ('order_notes', models.TextField(blank=True, default='', null=True)),
                ('manufacture_notes', models.TextField(blank=True, default='', null=True)),
                ('delivery_notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60, null=True)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('office_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=60, null=True)),
                ('contact_notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('print_notes', models.TextField(blank=True, default='')),
                ('cut_notes', models.TextField(blank=True, default='')),
                ('pack_notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('SKU', models.CharField(blank=True, default='', max_length=20)),
                ('barcode', models.CharField(blank=True, default='', max_length=20)),
                ('overprint', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced', models.BooleanField(default=False, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ERP.product')),
            ],
        ),
    ]
