# Generated by Django 3.1.7 on 2021-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20210315_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(to='ERP.Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ManyToManyField(to='ERP.Product'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
