# Generated by Django 3.1.7 on 2021-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20210315_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_for_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
